sub-playbooks:
  - hello_world/playbook.yml
  - basic_types/playbook.yml
  - variable/playbook.yml
  - files/playbook.yml
  - templates/playbook.yml
  - option/playbook.yml
  - function/playbook.yml
  - loops/playbook.yml
  - mutability/playbook.yml
  - struct/playbook.yml
  - enum/playbook.yml
  - match/playbook.yml
  - tokenizer/playbook.yml
  - config/playbook.yml
  - conv/playbook.yml
  - monade/playbook.yml
